main: me.jdomi.chat.main
name: InfinityChat
version: 2.0.0
author: Jdomi
api-version: '1.20'
softdepend:
    - PlaceholderAPI
    - DiscordSRV
    - EssentialsDiscord
commands:
    ic-reload: { description: 'Reloads the configuration' }
    infinitychat-reload: { description: 'Reloads the configuration' }
    cc: { description: 'Clears the servers chat' }
    clearchat: { description: 'Clears the servers chat' }
    ic: { description: 'Download and find out! ;)' }
    infinitychat: { description: 'Download and find out! ;)' }
    staff: { description: 'Staff Chat' }
    s: { description: 'Staff Chat' }
    local: { description: 'Local Chat' }
    l: { description: 'Local Chat' }
    announce: { description: 'Announce' }
    anc: { description: 'Announce' }
    mute: { description: 'Mute' }
    m: { description: 'Mute' }
    unmute: { description: 'Unmute' }
    um: { description: 'Unmute' }
permissions:
    ic.reload: { description: 'Access for /ic-reload' }
    ic.cc: { description: 'Access for /cc' }
    ic.bypass: { description: 'Bypass the chat spam filter' }
    ic.placeholderChat: { description: 'Allow chat placeholders'}
    ic.staff: { description: 'Staff Perm' }
    ic.announce: { description: 'Access to /announce'}
    ic.mute: {'Access to /mute'}
    ic.shout: {'Allows you to bypass the capital letter limit'}