# Made with <3 by Jdomi
# InfinityChat 1.4.0
#
#  ╭━━╮╱╱╭━╮╱╱╱╱╭╮╱╱╱╱╭━━━┳╮╱╱╱╱╭╮
#  ╰┫┣╯╱╱┃╭╯╱╱╱╭╯╰╮╱╱╱┃╭━╮┃┃╱╱╱╭╯╰╮
#  ╱┃┃╭━┳╯╰┳┳━╮┣╮╭╋╮╱╭┫┃╱╰┫╰━┳━┻╮╭╯
#  ╱┃┃┃╭╋╮╭╋┫╭╮╋┫┃┃┃╱┃┃┃╱╭┫╭╮┃╭╮┃┃
#  ╭┫┣┫┃┃┃┃┃┃┃┃┃┃╰┫╰━╯┃╰━╯┃┃┃┃╭╮┃╰╮
#  ╰━━┻╯╰┻╯╰┻╯╰┻┻━┻━╮╭┻━━━┻╯╰┻╯╰┻━╯
#  ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
#  ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯

# Delay in seconds

# Nopermission chat format will only apply to those who dont have any group permissions

# Do not touch server-version, plugin-version and last-pluginversion

# Permissions e.g. the permission with this would be message.owner

plugin-prefix: "<GRADIENT:fcc600>InfinityChat</GRADIENT:a4fc00>&7 » "

settings:
  debugMode: "false"
  updateChecking: "true"
  joinFormat: "true"
  leaveFormat: "true"
  chatFormatting: "true"
  hexChat: "true"
  antiSwear: "true"
  motd: "true"
  antiChatRepeat: "true"
  chatCooldown: "true"
  motdDelayTime: "3"
  chatCooldownTime: "3"
  chatFormat: "%prefix%&7%player_name% &b%arrow% &7%message%"
  noGroupChatFormat: "&7%player_name% &b%arrow% &7%message%"
  staffChatFormat: "<GRADIENT:a31d00>[ICStaff]</GRADIENT:ff2d00>&7 %prefix%&8%player_name%&b %arrow%&7%message%"
  noGroupStaffChatFormat: "<GRADIENT:a31d00>[ICStaff]</GRADIENT:ff2d00>&7 &8%player_name%&b %arrow%&7%message%"
  permPrefix: "message"
  joinSound:
    enabled: "true"
    delay: "3"
    sound: "ENTITY_PLAYER_LEVELUP"
  joinParticle:
    enabled: "true"
    delay: "3"
    particle: "CRIT"
    multiplier: "2"

server-version: "none"
plugin-version: "none"
last-plugin-version: "none"